import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { useState } from 'react'
import { useRouter } from 'next/router'

export default function Home() {
  
  const router = useRouter()

  const [formData, setFormDate] = useState({
    firstName: '',
    username:''
  })

  const Checklogin = () => {
    console.log(formData.firstName)
    console.log(formData)

    if(formData.username !== null) {
      router.push( {
        pathname: './counter',
        query: {
          username: formData.username
        }
      })
    }
  }



  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <label>First name:</label>
        <input
        type="type"
        id="first"
        name="first"
       pattern="[A-Z]{1}[a-z]{2-10}"
       title="The first letter should capitalized"
       onChange={(e => setFormDate({...formData, firstName: e.target.value}))}
       value={formData.first}
      />

      <label>Username:</label>
      <input
      type="type"
      id="username"
      name="username"
      required
      title="Type your username"
      minLength="5"
      maxLength="10"
      onChange={(e => setFormDate({...formData, username: e.target.value}))}
      value={formData.username}
      />
      <button type="submit" onClick={() => Checklogin()}>submit</button>
      </main>
      </div>

  )
}
